spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: exam-file
server:
  port: 18082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8887/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
