
server:
  port: 7001
spring:
  application:
    name: exam-users-provider
  #数据源连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_user?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: senge
    #druid连接池
    druid:
      initial-size: 5   #初始化连接大小
      min-idle: 5 #最小连接池数量
      max-active: 20  #最大连接池数量
      max-wait: 60000 #获取连接时最大的等待时间
      time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测
      min-evictable-idle-time-millis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
      test-while-idle: true #申请连接的时候检测，建议配置为true，不影响性能，并且保证安
      test-on-borrow: false #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大
  #rabbitmq
  rabbitmq:
    host: 118.25.144.199
    port: 5672
    username: guest
    password: guest
    #交换机和路由key
    verificationCode-exchange: verificationCode
    verificationCode-key: verificationCode
#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.coolyusen.exam.pojo.user
  mapper-locations: classpath:mapper/*/*Mapper.xml
#eureka
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8887/eureka/
    register-with-eureka: true